# Generated by Django 5.2 on 2026-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('published_date', models.DateTimeField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('reading_minute', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('tg_link', models.URLField()),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
